// frontend/src/views/settings/MemberManagement.vue
<template>
  <div style="padding: 24px">
    <div style="display: flex; justify-content: space-between; margin-bottom: 16px">
      <h3>成员管理</h3>
      <a-button type="primary" @click="showAdd = true"><PlusOutlined /> 添加成员</a-button>
    </div>
    <a-table :columns="columns" :data-source="users" row-key="id" :loading="loading"
      :pagination="{ current: page, total, pageSize: 20, onChange: (p: number) => loadUsers(p) }" size="middle">
      <template #bodyCell="{ column, record }">
        <template v-if="column.key === 'role'">
          <a-select :value="record.role" @change="(v: any) => userApi.update(record.id, { role: v }).then(() => loadUsers(page))" size="small" style="width: 100px"
            :options="[{value:'SUPER_ADMIN',label:'超管'},{value:'ADMIN',label:'管理员'},{value:'MEMBER',label:'成员'}]" />
        </template>
        <template v-if="column.key === 'identity'">
          <a-select :value="record.identity" @change="(v: any) => userApi.update(record.id, { identity: v }).then(() => loadUsers(page))" size="small" style="width: 80px"
            :options="[{value:'TEST',label:'测试'},{value:'DEV',label:'研发'},{value:'PRODUCT',label:'产品'}]" />
        </template>
        <template v-if="column.key === 'status'">
          <a-tag :color="record.status === 1 ? 'success' : 'error'">{{ record.status === 1 ? '启用' : '禁用' }}</a-tag>
        </template>
        <template v-if="column.key === 'action'">
          <a-button type="link" size="small" @click="userApi.toggleStatus(record.id).then(() => loadUsers(page))">
            {{ record.status === 1 ? '禁用' : '启用' }}
          </a-button>
        </template>
      </template>
    </a-table>
    <a-modal v-model:open="showAdd" title="添加成员" @ok="addUser">
      <a-form layout="vertical">
        <a-form-item label="用户名"><a-input v-model:value="form.username" /></a-form-item>
        <a-form-item label="显示名"><a-input v-model:value="form.displayName" /></a-form-item>
        <a-form-item label="身份">
          <a-select v-model:value="form.identity" :options="[{value:'TEST',label:'测试'},{value:'DEV',label:'研发'},{value:'PRODUCT',label:'产品'}]" />
        </a-form-item>
        <a-form-item label="项目权限">
          <a-select mode="multiple" v-model:value="form.projectIds" :options="projects.map((p: any) => ({ value: p.id, label: p.name }))" />
        </a-form-item>
      </a-form>
      <a-typography-text type="secondary">默认密码: wps123456</a-typography-text>
    </a-modal>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue';
import { message } from 'ant-design-vue';
import { PlusOutlined } from '@ant-design/icons-vue';
import { userApi, projectApi } from '../../api';
import type { User, Project } from '../../types';

const users = ref<User[]>([]);
const projects = ref<Project[]>([]);
const loading = ref(false);
const page = ref(1);
const total = ref(0);
const showAdd = ref(false);
const form = reactive({ username: '', displayName: '', identity: 'TEST', projectIds: [] as string[] });

async function loadUsers(p = 1) {
  loading.value = true;
  try { const res = await userApi.list(p, 20); users.value = res.data.records; total.value = res.data.total; page.value = p; }
  finally { loading.value = false; }
}
onMounted(() => { loadUsers(); projectApi.listAll().then(r => projects.value = r.data); });

async function addUser() {
  await userApi.create({ ...form, password: 'wps123456' });
  message.success('创建成功'); showAdd.value = false; Object.assign(form, { username: '', displayName: '', identity: 'TEST', projectIds: [] }); loadUsers();
}

const columns = [
  { title: '用户名', dataIndex: 'username' }, { title: '显示名', dataIndex: 'displayName' },
  { title: '角色', key: 'role', width: 120 }, { title: '身份', key: 'identity', width: 100 },
  { title: '状态', key: 'status', width: 80 }, { title: '操作', key: 'action', width: 100 },
];
</script>

// frontend/src/pages/settings/MemberManagement.tsx
import { useState, useEffect } from 'react';
import { Table, Button, Modal, Form, Input, Select, Tag, Space, message, Typography } from 'antd';
import { PlusOutlined, UserOutlined } from '@ant-design/icons';
import { userApi, projectApi } from '../../api';
import type { User, Project } from '../../types';

const ROLE_MAP: Record<string, { label: string; color: string }> = {
  SUPER_ADMIN: { label: '超管', color: 'red' },
  ADMIN: { label: '管理员', color: 'orange' },
  MEMBER: { label: '成员', color: 'blue' },
};

const IDENTITY_MAP: Record<string, string> = { TEST: '测试', DEV: '研发', PRODUCT: '产品' };

export default function MemberManagement() {
  const [users, setUsers] = useState<User[]>([]);
  const [projects, setProjects] = useState<Project[]>([]);
  const [loading, setLoading] = useState(false);
  const [modalOpen, setModalOpen] = useState(false);
  const [form] = Form.useForm();
  const [page, setPage] = useState(1);
  const [total, setTotal] = useState(0);

  const loadUsers = async (p = 1) => {
    setLoading(true);
    try {
      const res = await userApi.list(p, 20);
      setUsers(res.data.records);
      setTotal(res.data.total);
      setPage(p);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadUsers();
    projectApi.listAll().then(res => setProjects(res.data));
  }, []);

  const handleCreate = async () => {
    const values = await form.validateFields();
    await userApi.create({
      ...values,
      password: 'wps123456',
    });
    message.success('创建成功，默认密码 wps123456');
    setModalOpen(false);
    form.resetFields();
    loadUsers();
  };

  const handleRoleChange = async (id: number, role: string) => {
    await userApi.update(id, { role } as Partial<User>);
    message.success('角色已更新');
    loadUsers(page);
  };

  const handleIdentityChange = async (id: number, identity: string) => {
    await userApi.update(id, { identity } as Partial<User>);
    message.success('身份已更新');
    loadUsers(page);
  };

  const handleToggleStatus = async (id: number) => {
    await userApi.toggleStatus(id);
    message.success('状态已更新');
    loadUsers(page);
  };

  const columns = [
    { title: '用户名', dataIndex: 'username', key: 'username' },
    { title: '显示名', dataIndex: 'displayName', key: 'displayName' },
    {
      title: '角色', dataIndex: 'role', key: 'role', width: 130,
      render: (role: string, record: User) => (
        <Select
          size="small"
          value={role}
          onChange={val => handleRoleChange(record.id, val)}
          options={Object.entries(ROLE_MAP).map(([k, v]) => ({ value: k, label: v.label }))}
          style={{ width: 100 }}
        />
      ),
    },
    {
      title: '身份', dataIndex: 'identity', key: 'identity', width: 120,
      render: (identity: string, record: User) => (
        <Select
          size="small"
          value={identity}
          onChange={val => handleIdentityChange(record.id, val)}
          options={Object.entries(IDENTITY_MAP).map(([k, v]) => ({ value: k, label: v }))}
          style={{ width: 80 }}
        />
      ),
    },
    {
      title: '状态', dataIndex: 'status', key: 'status', width: 80,
      render: (status: number) => <Tag color={status === 1 ? 'success' : 'error'}>{status === 1 ? '启用' : '禁用'}</Tag>,
    },
    {
      title: '操作', key: 'action', width: 100,
      render: (_: unknown, record: User) => (
        <Button type="link" size="small" onClick={() => handleToggleStatus(record.id)}>
          {record.status === 1 ? '禁用' : '启用'}
        </Button>
      ),
    },
  ];

  return (
    <div style={{ padding: 24 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 16 }}>
        <Typography.Title level={4}>成员管理</Typography.Title>
        <Button type="primary" icon={<PlusOutlined />} onClick={() => setModalOpen(true)}>添加成员</Button>
      </div>

      <Table
        rowKey="id"
        columns={columns}
        dataSource={users}
        loading={loading}
        pagination={{ current: page, total, pageSize: 20, onChange: p => loadUsers(p) }}
        size="middle"
      />

      <Modal title="添加成员" open={modalOpen} onOk={handleCreate} onCancel={() => { setModalOpen(false); form.resetFields(); }}>
        <Form form={form} layout="vertical">
          <Form.Item name="username" label="用户名" rules={[{ required: true }]}>
            <Input prefix={<UserOutlined />} placeholder="用户名" />
          </Form.Item>
          <Form.Item name="displayName" label="显示名" rules={[{ required: true }]}>
            <Input placeholder="显示名称" />
          </Form.Item>
          <Form.Item name="identity" label="成员身份" rules={[{ required: true }]}>
            <Select options={Object.entries(IDENTITY_MAP).map(([k, v]) => ({ value: k, label: v }))} />
          </Form.Item>
          <Form.Item name="projectIds" label="项目权限">
            <Select mode="multiple" options={projects.map(p => ({ value: p.id, label: p.name }))} placeholder="选择项目" />
          </Form.Item>
        </Form>
        <Typography.Text type="secondary">默认密码: wps123456</Typography.Text>
      </Modal>
    </div>
  );
}
