// frontend/src/views/settings/ProjectManagement.vue
<template>
  <div style="padding: 24px">
    <div style="display: flex; justify-content: space-between; margin-bottom: 16px">
      <h3>项目空间管理</h3>
      <a-button type="primary" @click="editId = null; form.name = ''; form.description = ''; showModal = true"><PlusOutlined /> 创建项目</a-button>
    </div>
    <a-table :columns="columns" :data-source="projects" row-key="id" :loading="loading" :pagination="false" size="middle">
      <template #bodyCell="{ column, record }">
        <template v-if="column.key === 'action'">
          <a-space>
            <a-button type="link" size="small" @click="editId = record.id; form.name = record.name; form.description = record.description; showModal = true">编辑</a-button>
            <a-popconfirm title="确认删除?" @confirm="projectApi.delete(record.id).then(load)"><a-button type="link" size="small" danger>删除</a-button></a-popconfirm>
          </a-space>
        </template>
      </template>
    </a-table>
    <a-modal v-model:open="showModal" :title="editId ? '编辑项目' : '创建项目'" @ok="save">
      <a-form layout="vertical">
        <a-form-item label="项目名称"><a-input v-model:value="form.name" /></a-form-item>
        <a-form-item label="描述"><a-textarea v-model:value="form.description" /></a-form-item>
      </a-form>
    </a-modal>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue';
import { message } from 'ant-design-vue';
import { PlusOutlined } from '@ant-design/icons-vue';
import { projectApi } from '../../api';
import type { Project } from '../../types';

const projects = ref<Project[]>([]);
const loading = ref(false);
const showModal = ref(false);
const editId = ref<string | null>(null);
const form = reactive({ name: '', description: '' });

async function load() { loading.value = true; try { projects.value = (await projectApi.listAll()).data; } finally { loading.value = false; } }
onMounted(load);

async function save() {
  if (editId.value) { await projectApi.update(editId.value, form.name, form.description); }
  else { await projectApi.create(form.name, form.description); }
  message.success('保存成功'); showModal.value = false; load();
}

const columns = [
  { title: '项目名称', dataIndex: 'name' }, { title: '描述', dataIndex: 'description' },
  { title: '创建时间', dataIndex: 'createdAt', width: 180 }, { title: '操作', key: 'action', width: 160 },
];
</script>

// frontend/src/pages/settings/ProjectManagement.tsx
import { useState, useEffect } from 'react';
import { Table, Button, Modal, Form, Input, Space, message, Typography, Popconfirm } from 'antd';
import { PlusOutlined, DeleteOutlined, EditOutlined } from '@ant-design/icons';
import { projectApi } from '../../api';
import type { Project } from '../../types';

export default function ProjectManagement() {
  const [projects, setProjects] = useState<Project[]>([]);
  const [loading, setLoading] = useState(false);
  const [modalOpen, setModalOpen] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [form] = Form.useForm();

  const loadProjects = async () => {
    setLoading(true);
    try {
      const res = await projectApi.listAll();
      setProjects(res.data);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { loadProjects(); }, []);

  const handleSave = async () => {
    const values = await form.validateFields();
    if (editingId) {
      await projectApi.update(editingId, values.name, values.description);
      message.success('更新成功');
    } else {
      await projectApi.create(values.name, values.description);
      message.success('创建成功');
    }
    setModalOpen(false);
    form.resetFields();
    setEditingId(null);
    loadProjects();
  };

  const handleDelete = async (id: number) => {
    await projectApi.delete(id);
    message.success('删除成功');
    loadProjects();
  };

  const handleEdit = (project: Project) => {
    setEditingId(project.id);
    form.setFieldsValue({ name: project.name, description: project.description });
    setModalOpen(true);
  };

  const columns = [
    { title: '项目名称', dataIndex: 'name', key: 'name' },
    { title: '描述', dataIndex: 'description', key: 'description' },
    { title: '创建时间', dataIndex: 'createdAt', key: 'createdAt', width: 180 },
    {
      title: '操作', key: 'action', width: 160,
      render: (_: unknown, record: Project) => (
        <Space>
          <Button type="link" size="small" icon={<EditOutlined />} onClick={() => handleEdit(record)}>编辑</Button>
          <Popconfirm title="确认删除?" onConfirm={() => handleDelete(record.id)}>
            <Button type="link" size="small" danger icon={<DeleteOutlined />}>删除</Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <div style={{ padding: 24 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 16 }}>
        <Typography.Title level={4}>项目空间管理</Typography.Title>
        <Button type="primary" icon={<PlusOutlined />} onClick={() => { setEditingId(null); form.resetFields(); setModalOpen(true); }}>创建项目</Button>
      </div>

      <Table rowKey="id" columns={columns} dataSource={projects} loading={loading} pagination={false} size="middle" />

      <Modal title={editingId ? '编辑项目' : '创建项目'} open={modalOpen} onOk={handleSave} onCancel={() => { setModalOpen(false); setEditingId(null); form.resetFields(); }}>
        <Form form={form} layout="vertical">
          <Form.Item name="name" label="项目名称" rules={[{ required: true }]}>
            <Input placeholder="输入项目名称" />
          </Form.Item>
          <Form.Item name="description" label="描述">
            <Input.TextArea placeholder="项目描述" />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
}
