// frontend/src/views/Login.vue
<template>
  <div class="login-bg">
    <a-card class="login-card">
      <div style="text-align: center; margin-bottom: 32px">
        <h1 style="color: #1677ff; margin-bottom: 8px">CaseFlow</h1>
        <a-typography-text type="secondary">测试用例管理平台</a-typography-text>
      </div>
      <a-form :model="form" @finish="handleLogin" size="large">
        <a-form-item name="username" :rules="[{ required: true, message: '请输入用户名' }]">
          <a-input v-model:value="form.username" placeholder="用户名">
            <template #prefix><UserOutlined /></template>
          </a-input>
        </a-form-item>
        <a-form-item name="password" :rules="[{ required: true, message: '请输入密码' }]">
          <a-input-password v-model:value="form.password" placeholder="密码">
            <template #prefix><LockOutlined /></template>
          </a-input-password>
        </a-form-item>
        <a-form-item>
          <a-button type="primary" html-type="submit" :loading="loading" block style="height: 44px">登 录</a-button>
        </a-form-item>
      </a-form>
      <a-typography-text type="secondary" style="font-size: 12px">默认账号: admin / wps123456</a-typography-text>
    </a-card>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref } from 'vue';
import { useRouter } from 'vue-router';
import { message } from 'ant-design-vue';
import { UserOutlined, LockOutlined } from '@ant-design/icons-vue';
import { authApi, projectApi } from '../api';
import { useAppStore } from '../stores/app';

const router = useRouter();
const store = useAppStore();
const loading = ref(false);
const form = reactive({ username: '', password: '' });

async function handleLogin() {
  loading.value = true;
  try {
    const res = await authApi.login(form.username, form.password);
    localStorage.setItem('token', res.data.token);
    const [userRes, projRes] = await Promise.all([authApi.currentUser(), projectApi.list()]);
    store.setUser(userRes.data);
    store.setProjects(projRes.data);
    if (!store.currentProject && projRes.data.length > 0) store.setCurrentProject(projRes.data[0]);
    message.success('登录成功');
    router.push('/');
  } catch { /* handled */ } finally { loading.value = false; }
}
</script>

<style scoped>
.login-bg {
  height: 100vh; display: flex; justify-content: center; align-items: center;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}
.login-card { width: 420px; border-radius: 12px; box-shadow: 0 20px 60px rgba(0,0,0,0.3); }
</style>

// frontend/src/pages/Login.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Form, Input, Button, Card, Typography, message } from 'antd';
import { UserOutlined, LockOutlined } from '@ant-design/icons';
import { authApi, projectApi } from '../api';
import useStore from '../stores/useStore';

const { Title, Text } = Typography;

export default function LoginPage() {
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();
  const { setUser, setProjects, setCurrentProject } = useStore();

  const onFinish = async (values: { username: string; password: string }) => {
    setLoading(true);
    try {
      const res = await authApi.login(values.username, values.password);
      localStorage.setItem('token', res.data.token);
      const [userRes, projRes] = await Promise.all([authApi.currentUser(), projectApi.list()]);
      setUser(userRes.data);
      setProjects(projRes.data);
      if (projRes.data.length > 0) setCurrentProject(projRes.data[0]);
      message.success('登录成功');
      navigate('/');
    } catch {
      // error handled by interceptor
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{
      height: '100vh',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    }}>
      <Card style={{ width: 420, borderRadius: 12, boxShadow: '0 20px 60px rgba(0,0,0,0.3)' }}>
        <div style={{ textAlign: 'center', marginBottom: 32 }}>
          <Title level={2} style={{ marginBottom: 8, color: '#1677ff' }}>CaseFlow</Title>
          <Text type="secondary">测试用例管理平台</Text>
        </div>
        <Form onFinish={onFinish} size="large">
          <Form.Item name="username" rules={[{ required: true, message: '请输入用户名' }]}>
            <Input prefix={<UserOutlined />} placeholder="用户名" />
          </Form.Item>
          <Form.Item name="password" rules={[{ required: true, message: '请输入密码' }]}>
            <Input.Password prefix={<LockOutlined />} placeholder="密码" />
          </Form.Item>
          <Form.Item>
            <Button type="primary" htmlType="submit" loading={loading} block style={{ height: 44 }}>
              登 录
            </Button>
          </Form.Item>
        </Form>
        <Text type="secondary" style={{ fontSize: 12 }}>默认账号: admin / wps123456</Text>
      </Card>
    </div>
  );
}
